---
- name: Updating etc/hosts
  import_playbook: update-etc-hosts.yml

- name:  Extra apt packages
  import_playbook: install-apt-packages.yml

- name:  Extra pip packages
  import_playbook: install-pip-modules.yml

- name:  Extra Hadoop Config
  import_playbook: hadoop_logs_permissions.yml
  
- name:  Extra Spark Config
  import_playbook: spark_config_update.yml
  
- name:  Twitter Stopwords
  import_playbook: copy_stopwords.yml