---
#- name: Add User  # Comment this as cutleradmin is used
#  sudo: yes
#  user: name={{user}} shell=/bin/bash append=yes
#  when: add_user


- name: Check if there is a public key
  shell: "ls /home/{{ user }}/.ssh | grep '.pub' | wc -l"
  register: key_exist
  ignore_errors: true

- name: Generate ssh keypair
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: "key_exist.stdout == '0' and generate_key"
  
- name: Get Public Key From Hadoop Node
  fetch: 
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /tmp/id_{{ ansible_host }}_{{ user }}.pub
    flat: yes  

#- name: Add Hadoop Public Key 
#  authorized_key: 
#    user={{ user }} 
#    key="{{ lookup('file', '/tmp/id_{{ ansible_host }}_{{user}}.pub') }}"    
    
