---
  - name: Include Matlab default variables (in default/main.yml file).
    include_vars: main.yml
    
  - name: Install unzip for unarchiving
    apt:
      name: unzip
   
  - name: Check for MATLAB files
    stat:
      path: "{{ matlabDefaultPath }}"
    register: matlab_files

  - name: Download MATLAB
    get_url:
      url: "{{ matlabPackageUri }}"
      dest: "{{ matlabLocalZipPath }}"
    when: matlab_files.stat.exists == False

  - name: Create unzip path
    file:
      dest: "{{ matlabUnzippedPath }}"
      state: directory
    when: matlab_files.stat.exists == False

  - name: Unzip MATLAB
    unarchive:
      copy: no
      src: "{{ matlabLocalZipPath }}"
      dest: "{{ matlabUnzippedPath }}"
    when: matlab_files.stat.exists == False

  - name: Install MATLAB
    command: ./install -mode silent -agreeToLicense yes
    args:
      chdir: "{{ matlabUnzippedPath }}"
      creates: "{{ matlabDefaultPath }}"
    when: matlab_files.stat.exists == False

  - name: Clean Up
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ matlabLocalZipPath }}"
      - "{{ matlabUnzippedPath }}"
    when: matlab_files.stat.exists == False
