---
#- name: Create Hadoop Path
#  file: 
#    path: "{{ item }}"
#    owner: "{{ user }}"
#    group: "{{ group }}"
#    state: directory
#    mode: 0755
#  with_items:
#    - "{{ hadoop_create_path }}"

#- name: Download hadoop
#  get_url:
#    url: "{{ hadoop_download_url }}"
#    dest: "{{ hadoop_tmp }}/hadoop-{{hadoop_version}}.tar.gz"
#  
#- name: Unzip Hadoop  
#  shell: "tar zxf {{ hadoop_tmp }}/hadoop-{{hadoop_version}}.tar.gz -C {{ hadoop_home }}"

- include: config_hadoop.yml
  when: config_hadoop
