
- name: reload systemd configuration
  sudo: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart elasticsearch
  sudo: yes
  service: name=elasticsearch state=restarted enabled=yes
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
