---
user: "cutleradmin"
group: "cutleradmin"

# java version - require hadoop nodes to have openjdk-8-jdk
jvm_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
#jvm_home: "/usr/lib/jvm/java-11-openjdk-amd64/"

hadoop_download_url: https://archive.apache.org/dist/hadoop/common/hadoop-3.2.0/hadoop-3.2.0.tar.gz

# hadoop basic vars
hadoop_home: "/home/{{ cutler_admin }}/"
hadoop_version: "3.2.0"
hadoop_path: "/home/{{ cutler_admin }}/hadoop-{{ hadoop_version }}/"
hadoop_config_path: "/home/{{ cutler_admin }}/hadoop-{{ hadoop_version }}/etc/hadoop/"
hadoop_tmp: "/home/{{ cutler_admin }}/tmp/"
hadoop_dfs_name: "/home/{{ cutler_admin }}/dfs/namenode"
hadoop_dfs_data: "/home/{{ cutler_admin }}/dfs/datanode"
hadoop_log_path: "/home/{{ cutler_admin }}/hadoop_logs"

hadoop_create_path:
  - "{{ hadoop_path }}"
  - "{{ hadoop_tmp }}"
  - "{{ hadoop_dfs_name }}"
  - "{{ hadoop_dfs_data }}"
  - "{{ hadoop_log_path }}"


# hadoop configration 
master_ip: 172.16.34.10
resource_ip: 172.16.34.44
dn1_ip: 172.16.34.20
dn2_ip: 172.16.34.21
dn3_ip: 172.16.34.22

hdfs_port: 9000
core_site_properties:
  - {
      "name":"fs.defaultFS",
      "value":"hdfs://{{ master_ip }}:{{ hdfs_port }}"
  }
  - {
      "name":"hadoop.tmp.dir",
      "value":"file:{{ hadoop_tmp }}"
  }
  - {
    "name":"io.file.buffer.size",
    "value":"131072"
  }

dfs_secondary_namenode_httpport: 50090
hdfs_site_properties:
  - {
      "name":"dfs.namenode.secondary.http-address",
      "value":"{{ master_ip }}:{{ dfs_secondary_namenode_httpport }}"
  }
  - {
      "name":"dfs.namenode.name.dir",
      "value":"file:{{ hadoop_dfs_name }}"
  }
  - {
      "name":"dfs.datanode.data.dir",
      "value":"file:{{ hadoop_dfs_data }}"
  }
  - {
      "name":"dfs.replication",
      "value":"{{ groups['hadoopDN_servers']|length }}"
  }
  - {
    "name":"dfs.webhdfs.enabled",
    "value":"true"
  }

mapred_site_properties:
 - {
   "name": "mapreduce.framework.name",
   "value": "yarn"
 }
 - {
   "name": "mapreduce.admin.user.env",
   "value": "HADOOP_MAPRED_HOME=$HADOOP_HOME"
 }
 - {
   "name":"yarn.app.mapreduce.am.env",
   "value":"HADOOP_MAPRED_HOME=$HADOOP_HOME"
 }
 - {
   "name": "mapreduce.map.env",
   "value": "HADOOP_MAPRED_HOME=$HADOOP_HOME"
 }
 - {
   "name":"mapreduce.reduce.env",
   "value":"HADOOP_MAPRED_HOME=$HADOOP_HOME"
 } 

# default port for yarn
#hadoop_default_ports:
yarn_resourcemanager_webapp_port: 8088
yarn_resourcemanager_webapp_https_port: 8090
yarn_resourcemanager_port: 8032 
yarn_resourcemanager_default_port: 8050
yarn_resourcemanager_tracker_port: 8025
yarn_resourcemanager_scheduler_port: 8030
yarn_resourcemanager_admin_port: 8141
yarn_nodemanager_port: 45454
yarn_nodemanager_webapp_port: 8042
yarn_timeline_service_port: 10200
yarn_timeline_service_webapp_port: 8188
yarn_timeline_service_webapp_https_port: 8190
yarn_log_server_url: 19888
datanode_datatransfer_port: 9866
dfs_datanode_http_address: 50075
dfs_datanode_https_address: 50475
dfs_datanode_address: 50010
dfs_datanode_ipc_address: 50020

yarn_site_properties:
  - {
    "name":"yarn.resourcemanager.hostname",
    "value":"{{ resource_ip }}"
  }


dashbord_port: 9870
